# Generated by Django 4.1 on 2023-03-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=20, unique=True, verbose_name="用户名"),
                ),
                ("password", models.CharField(max_length=20, verbose_name="密码")),
                ("name", models.CharField(max_length=20, verbose_name="账户名字")),
            ],
            options={
                "db_table": "userinfo",
            },
        ),
    ]
